apiVersion: enterprise.splunk.com/v1
kind: Standalone
metadata:
  name: s1
  finalizers:
    - enterprise.splunk.com/delete-pvc
spec:
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "4"
  volumes:
    - name: tls
      secret:
        secretName: s1-tls
    - name: certtool
      configMap:
        name: certtool
        defaultMode: 0777
  serviceTemplate:
    spec:
      ports:
        - name: tls-s2s
          port: 9998
          protocol: TCP
          targetPort: 9998
  defaults: |-
    splunk:
      apps_location:
        - "http://splunk-apps/addonfactory_all_indexes.spl"
      conf:
        - key: web
          value:
            content:
              settings:
                "tools.proxy.on": "true"
                "tools.proxy.base": "https://s1.${DOMAIN_NAME}"
        - key: inputs
          value:
            content:
              http:
                enableSSL: "0"
              SSL:
                serverCert: /opt/splunk/etc/certs/certmanager.pem
                sslPassword: password
                requireClientCert: false
              "splunktcp-ssl:9998":
                disabled: "0"
        - key: server
          value:
            content:
              sslConfig:
                certCreateScript: /mnt/certtool/merge.sh 
                sslPassword: password
                serverCert: /opt/splunk/etc/certs/certmanager.pem
