---
apiVersion: enterprise.splunk.com/v1
kind: ClusterMaster
metadata:
  name: s1cm
  finalizers:
    - enterprise.splunk.com/delete-pvc
spec:
  licenseMasterRef:
    name: s1
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"
  volumes:
    - name: tls
      secret:
        secretName: s1-cm-tls
    - name: certtool
      configMap:
        name: certtool
        defaultMode: 0777
        
  defaults: |-
    splunk:
      conf:
        - key: web
          value:
            content:
              settings:
                "tools.proxy.on": "true"
                "tools.proxy.base": "https://s1-cm.${DOMAIN_NAME}"        
        - key: server
          value:
            content:
              sslConfig:
                certCreateScript: /mnt/certtool/merge.sh 
                sslPassword: password
                serverCert: /opt/splunk/etc/certs/certmanager.pem
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: s1-cm-cert
spec:
  # Secret names are always required.
  secretName: s1-cm-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - ${DOMAIN_NAME}
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: s1-cm
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - s1-cm.${DOMAIN_NAME}
    - splunk-s1cm-indexer-service.splunk.svc.cluster.local

  # uris:
  # - spiffe://cluster.local/ns/sandbox/sa/example
  # # Issuer references are always required.
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: s1-cm
spec:
  gateways:
    - istio-system/shared-gateway
  hosts:
    - s1-cm.${DOMAIN_NAME}
  http:
    - name: "ui_insecure"
      match:
        - port: 80
      route:
        - destination:
            host: splunk-s1cm-cluster-master-service.splunk.svc.cluster.local
            port:
              number: 8000
    - name: "ui"
      match:
        - port: 443
      route:
        - destination:
            host: splunk-s1cm-cluster-master-service.splunk.svc.cluster.local
            port:
              number: 8000
          headers:
            request:
              set:
                "X-Forwarded-Host": "s1-cm.${DOMAIN_NAME}"
                "X-Forwarded-Port": "443"
                "X-Forwarded-Proto": https

    - name: "mgmt"
      match:
        - port: 8089
      route:
        - destination:
            host: splunk-s1cm-cluster-master-service.splunk.svc.cluster.local
            port:
              number: 8089
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: s1cm
spec:
  host: splunk-s1cm-cluster-master-service.splunk.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 8089
        tls:
          mode: SIMPLE
